### ISSUE TITLE
Saving/loading background image not working; also can't load mask image

### ISSUE THREAD

**Issue by jameswaters** [swarm-lab/trackR#12]
##### System information (version)

- trackR => 0.1.1
- Operating System / Platform => Mac OS X 10.9.5
- R => 3.3.3
- CMake => 3.13.1

##### Detailed description

Video loaded and background estimated. On clicking "Save background file", am prompted with a dialog box to choose a directory and file name for the .png file. Despite selecting an appropriate directory and file name, after clicking "Save", the dialog box goes away without error... and no image is actually saved. I've repeated this with other directories and file names, with the same result.

Three additional points of note:
 - In the background image save dialog, I also cannot make a new directory. Despite the option, following the steps to make a new folder doesn't actually make one, no error is given, the directory just isn't made.
 - I also cannot load a background image (e.g. one from Simon) based on the same video clip I'm working with.
 - I also cannot load a mask image. No error is given.

![image](https://user-images.githubusercontent.com/6729255/49982398-5d127480-ff2a-11e8-93f9-ee81df01f295.png)

Javascript console:

shinyapp.js:310 Uncaught TypeError: Cannot read property 'readyState' of null
    at ShinyApp.$sendMsg (shinyapp.js:310)
    at ShinyApp.sendInput (shinyapp.js:140)
    at input_rate.js:210

R Console:

```
R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.69 (7328) x86_64-apple-darwin13.4.0]

[Workspace restored from /Users/james/.RData]
[History restored from /Users/james/.Rapp.history]

> library(trackR)
> trackR()
Loading required package: shiny

Attaching package: ‘Rvision’

The following objects are masked from ‘package:graphics’:

    frame, image

The following objects are masked from ‘package:base’:

    mean, merge, split, sum


Listening on http://127.0.0.1:4021
```

When I hit the "escape" key to get back my R console, this additional text was displayed:

```
Note: input array values outside the authorized range of [0;255]. Rescaling was performed.
Warning: Error in dir.create: invalid 'path' argument
Stack trace (innermost first):
    60: dir.create
    59: dirCreate
    58: observerFunc
     2: shiny::runApp
     1: trackR

```

**Comment by jameswaters** [comment]
This might be the most up to date version I can run on Mac OS 10.9.5.
Really didn’t want to have to upgrade the OS... but yes, i’ll have to try
on a newer machine.

**Comment by sjmgarnier** [comment]
@jameswaters Any luck? Can I close this issue and blame it on your out of date R installation? ;-)
