### ISSUE TITLE
TrackR crashes: when I add a mask

### ISSUE THREAD

**Issue by LMAllenJacobson** [swarm-lab/trackR#13]
##### System information (version)
- trackR => 0.20
- Rvision => 0.3.4
- ROpenCVLite => 0.2.40.1
- devtools => 2.0.1
- shiny => 1.2.0
- Operating System / Platform => macOS Mojave 10.14.3   
- R => 3.5.2
- CMake => 3.12

##### Detailed description

When I add a mask, trackR crashes and gives the error listed below. My video and mask file types are MOV and PNG. The infor for the files are the following:

**Movie**
Kind: QuickTime movie
Size: 28,360,298 bytes (29.3 MB on disk)
Dimensions: 1080 × 1920
Codecs: AAC, Timed Metadata, HEVC
Color profile: HD (1-1-1)
Duration: 00:20
Audio channels: Mono
Encoding software: 12.1.3

**Mask**
Kind: PNG image
Size: 45,789 bytes (49 KB on disk)
Dimensions: 1080 × 1920
Color space: RGB
Color profile: sRGB IEC61966-2.1
Alpha channel: Yes

##### Steps to reproduce

```.r
> trackR()

Listening on http://127.0.0.1:7368
Error in _multiply: OpenCV(4.0.1) /private/var/folders/m7/khzj_2v15rncc7_9mkntdpk00000gp/T/RtmpgglNp3/R.INSTALL7b22afccae6/ROpenCVLite/src/opencv-4.0.1/modules/core/src/arithm.cpp:663: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
  52: <Anonymous>
```

**Comment by sjmgarnier** [comment]
@LMAllenJacobson This is because your mask has an alpha channel. I will fix this in a future release, but in the meantime you can save your png mask without the alpha channel, this should do the trick.

**Comment by LMAllenJacobson** [comment]
I duplicated the file and saved without the alpha channel. Here are the details of the updated mask file (I'm using the same video), and the new error:

**Mask**
Kind: PNG image
Size: 39,894 bytes (41 KB on disk)
Dimensions: 1080 × 1920
Color space: RGB
Color profile: sRGB IEC61966-2.1
Alpha channel: No


```
> trackR()

Listening on http://127.0.0.1:7368
Error in _multiply: OpenCV(4.0.1) /private/var/folders/m7/khzj_2v15rncc7_9mkntdpk00000gp/T/RtmpgglNp3/R.INSTALL7b22afccae6/ROpenCVLite/src/opencv-4.0.1/modules/core/src/arithm.cpp:663: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
  52: <Anonymous>
```

**Comment by sjmgarnier** [comment]
@LMAllenJacobson Can you send me this image as well? Thanks.

**Comment by sjmgarnier** [comment]
@LMAllenJacobson Ok, so the issue is that OpenCV does seem to require additional info to be able to orient properly videos taken from cell phones (I'm guessing this has to do with the phone recording its orientation - portrait or landscape - when shooting). So, if you open the video with Quicktime to extract an image, it will retain this recorded orientation (in your case, portrait), but this info doesn't seem to be read by OpenCV which always loads the video in landscape mode. This will require some investigation on my side to fix this in ROpenCVLite, but in the meantime, all you need to do is orient the mask to match the orientation in trackR.

**Comment by LMAllenJacobson** [comment]
Fixed! Thanks
