### ISSUE TITLE
TrackR crashes: when I estimate background

### ISSUE THREAD

**Issue by LMAllenJacobson** [swarm-lab/trackR#14]
##### System information (version)
- trackR => 0.20
- Rvision => 0.3.4
- ROpenCVLite => 0.2.40.1
- devtools => 2.0.1
- shiny => 1.2.0
- Operating System / Platform => macOS Mojave 10.14.3   
- R => 3.5.2
- CMake => 3.12

##### Detailed description

Sometimes, trackR crashes when I estimate the background. This seems to be a problem when I'm using larger video files and/or increasing the number of frames used to estimate the background.

##### Steps to reproduce
```.r
> trackR()

Listening on http://127.0.0.1:7368
Error in x$readFrame: Could not read the image matrix.  64: <Anonymous>
```

**Comment by sjmgarnier** [comment]
@LMAllenJacobson Would you mind sharing with me a video for which you get this issue?

**Comment by LMAllenJacobson** [comment]
sure. How should I send, e.mail?

**Comment by sjmgarnier** [comment]
@LMAllenJacobson Yes, an email works for me. Thanks.
