### ISSUE TITLE
visualize the tracked trajectory and manually edit wrong points

### ISSUE THREAD

**Issue by antoninocusumano** [swarm-lab/trackR#15]
Hi Simon Garnier
First of all, I want to congratulate you for this wonderful package for R. It is great! At the moment I am using it to track the movement of an insect in an open arena and it works very well. It would be great if it would be possible to edit the coordinates of the tracked object to correct mistakes. In fcat when the CSV file is generated and I plot the coordinates in R, I see sometimes "spikes" because the position of the tracked object is mistaken (see file attacked). Most of the times I can figure out how to exclude these "wrong" points if the mistake occurs at the beginning or end of the track or if the software detects multiple objects or different sizes. But if the "spikes" are at the middle then it is complicated. It would be great if you could implement a tool to visualize the tracked trajectory with the possibility to scroll the points to locate and manually editing wrong points
Anyway the software it is great!
[example for suggestion.pdf](https://github.com/swarm-lab/trackR/files/2999698/example.for.suggestion.pdf)

**Comment by sjmgarnier** [comment]
@antoninocusumano I'm working on it. However, I suspect your issue could be resolved by changing the look back and maximum distance parameters in the tracking tab. What values did you use?

**Comment by antoninocusumano** [comment]
Nice to know that you are already working on it! I use the default parameters (look back =5; maximum distance=30) but I can start playing with the settings to see if the issue can be fixed in this way. Thank for the suggestion

**Comment by sjmgarnier** [comment]
@antoninocusumano My guess is that if you reduce the maximum distance, you'll get rid of these "spikes".

**Comment by antoninocusumano** [comment]
Thanks.
For me you can close the issue
best
Antonino

Il 24.03.2019
16:35 Simon Garnier ha scritto: 

> @antoninocusumano [1] My guess is
that if you reduce the maximum distance, you'll get rid of these
"spikes". 
> 
> --
> You are receiving this because you were
mentioned.
> Reply to this email directly, view it on GitHub [2], or
mute the thread [3].
  


Con OpenStar hai Giga, SMS e i minuti che vuoi da 4,99€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 6 mesi di INFINTY! http://tisca.li/myopen
