### ISSUE TITLE
pop-up window: ERROR: Unknown module.

### ISSUE THREAD

**Issue by ndmtzn** [swarm-lab/trackR#16]
##### System information (version)
- trackR => 0.3.1
- Rvision => 0.3.4
- ROpenCVLite => 0.2.40.1
- devtools => 2.0.1
- shiny => 1.2.0
- Operating System / Platform => Win10 64 bit (v1803)
- R => 3.5.3
- R-Studio=> 1.1.463
- CMake => 3.14

##### Detailed description

After a the successful (?) installation of the necessary packages, I tried to run either of the following lines:

trackR("classic") 
trackR("quanta") 
trackR("tracktor")

When running them, a pop-up window appears with an "ERROR: Unknown module", and I get the following error in the console:

Listening on http://127.0.0.1:6317
Warning: Error in moduleUI: Unknown module.
  65: stop
  64: moduleUI
  46: ui [C:\R\R-3.5.3\library\trackR\trackR_classic/app.R#12]

The additional argument "launch.browser" gives the same error:

trackR("classic", launch.browser = rstudioapi::viewer)

**Comment by ndmtzn** [comment]
Screenshot of the pop-up window in attachement
![Clipboard01](https://user-images.githubusercontent.com/48906750/54920533-c0397d00-4f03-11e9-8bfb-bff4792b09f1.jpg)

**Comment by sjmgarnier** [comment]
@ndmtzn I will need to find a Windows machine to see if I can reproduce this problem (no issue on my Mac). In the meantime, what's the output of the following command?

```R
system.file("modules/", package = "trackR")
```

**Comment by ndmtzn** [comment]
Thank you for looking into this.
The output is as following:

[1] "C:/R/R-3.5.3/library/trackR/modules"

**Comment by sjmgarnier** [comment]
@ndmtzn I think I found the issue (it looks like on Windows, the "/" after "modules" is dropped in the output). Can you reinstall trackR and try again?

**Comment by ndmtzn** [comment]
I tried to reinstall trackR with the line:

devtools::install_github("swarm-lab/trackR", force=T)

The issue still persist.

**Comment by sjmgarnier** [comment]
@ndmtzn Oops, I forgot to push to the repo. Try now.

**Comment by ndmtzn** [comment]
It works! Thanks for the fast feedback.
