### ISSUE TITLE
trackR installation issues

### ISSUE THREAD

**Issue by goldenbrowntoast** [swarm-lab/trackR#17]
- trackR => 0.3 (attempted)
- Rvision => N/A
- ROpenCVLite => 0.3.410
- devtools => 2.0.2
- shiny => N/A
- Operating System / Platform => Mac OS Sierra
- R => 3.4.4
- CMake => 3.14.5

##### Detailed description

<I'm pretty new to R programming, so I'm sorry if my question is relatively dumb. I have ROpenCVLite installed and have gone through the long process to install OpenCV. Once I try to install trackR, I run into the following error:

Downloading GitHub repo swarm-lab/Rvision@master
✔  checking for file ‘/private/var/folders/rs/ksdxj0510fvg695s67wzynth0000gn/T/RtmpCevo4C/remotes162ee62f2f285/swarm-lab-Rvision-f793cb3/DESCRIPTION’ ...
─  preparing ‘Rvision’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (363ms)
─  checking for empty or unneeded directories
   Removed empty directory ‘Rvision/man/figures’
─  building ‘Rvision_0.3.5.tar.gz’
   
* installing *source* package ‘Rvision’ ...
+ set -e
+ /Library/Frameworks/R.framework/Resources/bin/Rscript -e 'if (!ROpenCVLite::isOpenCVInstalled()) {
  message("OpenCV is not installed on this system. It will be installed now.")
  ROpenCVLite::installOpenCV(force = TRUE)
}'
ARGUMENT '~+~~+~message("OpenCV~+~is~+~not~+~installed~+~on~+~this~+~system.~+~It~+~will~+~be~+~installed~+~now.")' __ignored__

ARGUMENT '~+~~+~ROpenCVLite::installOpenCV(force~+~=~+~TRUE)' __ignored__

ARGUMENT '}' __ignored__

Error: unexpected end of input
Execution halted
ERROR: configuration failed for package ‘Rvision’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rvision’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/rs/ksdxj0510fvg695s67wzynth0000gn/T//RtmpCevo4C/file162ee66a510a8/Rvision_0.3.5.tar.gz’ had non-zero exit status

Any insight onto why OpenCV isn't registering as installed? I get the same issue when I try to install just Rvision. Thanks for your time!>

**Comment by sjmgarnier** [comment]
@goldenbrowntoast It looks like you're using an old R version. Can you try with the latest version?

**Comment by goldenbrowntoast** [comment]
Haha, yeah, this got me through that error. I can't believe I didn't notice the "Rvision for 3.5". Sorry about that.
