### ISSUE TITLE
Crash on blob detection

### ISSUE THREAD

**Issue by rkadrian** [swarm-lab/trackR#19]
##### System information (version)
- trackR => 0.3.2
- Rvision => 0.3.6
- ROpenCVLite => 0.3.6
- devtools => 2.2.1
- shiny => 1.3.2
- Operating System / Platform => Mac OS Mojave
- R => 3.6.1
- CMake => 3.15.3

##### Detailed description

Hello again! I've managed to successfully load a video (in .m4v, converted from .avi), background, and mask, but trackR closes immediately upon clicking the "blob detection" tab. I've tried with video alone (no mask or BG) and still crashes. I imagine this is something simple--video format? Pasted below is the message received upon crash. Thank you!

##### Steps to reproduce

```
Warning: Error in <observer>: object 'cc' not found
  45: <observer> [/Library/Frameworks/R.framework/Versions/3.6/Resources/library/trackR/modules/blobClassicServer.R#69]
   2: shiny::runApp
   1: trackR
```

**Comment by sjmgarnier** [comment]
@rkadrian Could you please share the video with me so that I can try to reproduce the issue? Thanks.

**Comment by rkadrian** [comment]
Attempted to send via email--let me know if it doesn't come through. Thanks!

**Comment by rkadrian** [comment]
Fixed! Needed a background and the proper dimensions of mask image.
