### ISSUE TITLE
Not able to run trackR()

### ISSUE THREAD

**Issue by sgore25** [swarm-lab/trackR#20]
These are the specification of the system that I am using:

- Rvision => 0.1.1
- ROpenCVLite => 0.3.412.1
- devtools => 2.2.2
- shiny => 1.4.0.2
- Operating System / Platform => Mac OS Catalina
- R studio => 1.2.5019
- CMake => 3.15.5

When I try to run trackR(), a new window opens up but in that window, I get the following error.

**Warning: Error in container: unused arguments (id = outputId, class = "shiny-html-output", class = "good")**

Please let me know what can be done to solve this issue. Thank you.
<img width="904" alt="Screen Shot 2020-04-01 at 1 21 28 AM" src="https://user-images.githubusercontent.com/62715958/78101996-29758b00-73b7-11ea-9442-63638b3120c9.png">
<img width="630" alt="Screen Shot 2020-04-01 at 1 17 47 AM" src="https://user-images.githubusercontent.com/62715958/78101798-9b99a000-73b6-11ea-9bbc-0690bd708cea.png">

**Comment by sjmgarnier** [comment]
@sgore25 First, it looks like you have a very old version of Rvision. I suggest you update it. Try also updating the following packages: shinyBS, shinyFiles, shinyjs. Also, what is your version of R?

**Comment by sgore25** [comment]
I tried after updating Rvision(now it is 0.3.6). Also updates shinyBS,shinyFiles and shinyjs but still have the same issue. My R version is 3.6.1

**Comment by sjmgarnier** [comment]
@sgore25 Also, for good measure, you quit and restarted RStudio after all these updates? Just making sure there isn't an old version of one of the packages that was loaded in memory.

**Comment by sgore25** [comment]
Yes. I did restart R after all the updates.

**Comment by sjmgarnier** [comment]
@sgore25 I can't reproduce the error here. Would you have some time this week for a quick video call? My guess is that you have somewhere an old version of a Shiny dependency but it's hard to know without having a look at your R installation.

**Comment by sgore25** [comment]
Sure. That works. Does Friday noon EDT work for you?

**Comment by sjmgarnier** [comment]
@sgore25 No, I have a meeting then. But let's move this discussion to email: garnier@njit.edu.

**Comment by sgore25** [comment]
I have emailed you. Thank you.
