### ISSUE TITLE
Can't install Rvision

### ISSUE THREAD

**Issue by dougmills** [swarm-lab/trackR#21]
Hi, I am unable to install Rvision. 
I'm running the following:
- trackR => 0.3.2
- Rvision => 0.4.0
- ROpenCVLite => 0.4.43.0
- devtools => 2.3.0
- shiny => 1.2.0
- Operating System / Platform => 64 bit Win 10
- R => 3.6.0
- CMake => 3.17.3

OpenCV is installed but when I try to run trackR("Classic") or library(Rvision) the following message appears:
>Error in library(Rvision) : ‘Rvision’ is not a valid installed package

When I run:
 >devtools::install_github("swarm-lab/Rvision")
 Rvision is downloaded with the following output in the R console:

* installing *source* package 'Rvision' ...
** using non-staged installation via StagedInstall field
+ set -e
+ C:/PROGRA~1/R/R-36~1.0/bin/x64/Rscript.exe -e 'if (nzchar(Sys.getenv('\''CI'\'')) & !ROpenCVLite::isOpenCVInstalled()) ROpenCVLite::installOpenCV(batch = TRUE)'
+ C:/PROGRA~1/R/R-36~1.0/bin/x64/Rscript.exe -e 'if (nzchar(Sys.getenv('\''CI'\'')) & ROpenCVLite::isOpenCVInstalled() & 
	unlist(strsplit(as.character(utils::packageVersion('\''ROpenCVLite'\'')), '\''[.]'\''))[3] != gsub('\''[^0-9]'\'', '\'''\'', ROpenCVLite::opencvVersion())) 
	ROpenCVLite::installOpenCV(batch = TRUE)'
+ C:/PROGRA~1/R/R-36~1.0/bin/x64/Rscript.exe -e 'if (!ROpenCVLite::isOpenCVInstalled()) 
	{ cat('\''------------------ OPENCV NOT FOUND --------------------\n'\'') ; 
	  cat('\''\n'\'') ; 
	  cat('\''OpenCV was not found in your library. Please install OpenCV as follows:'\'') ; 
	  cat('\''\n'\'') ; 
	  cat('\''\n'\'') ; 
	  cat('\''ROpenCVLite::installOpenCV(batch = TRUE)\n'\'') ; 
	  cat('\''\n'\'') ; 
	  cat('\''--------------------------------------------------------\n'\'') ; 
	  cat('\''\n'\'') ; stop('\''OpenCV not found.'\'') }'
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 
	-I"C:/PROGRA~1/R/R-36~1.0/include" 
	-DNDEBUG -I"C:\Users\Doug\DOCUME~1\R\WIN-LI~1\3.6\opencv\include\opencv2" 
	-I"C:\Users\Doug\DOCUME~1\R\WIN-LI~1\3.6\opencv\include" 
	-I"C:\Users\Doug\DOCUME~1\R\WIN-LI~1\3.6\opencv\x86\mingw\bin" 
	-I"C:/Users/Doug/Documents/R/win-library/3.6/Rcpp/include" 
	-I"C:/Users/Doug/Documents/R/win-library/3.6/RcppArmadillo/include"     
	-IC:/Users/Doug/Documents/R/win-library/3.6/Rcpp/include   
	-O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o

c:/Rtools/mingw_32/bin/g++  -std=gnu++11 
	-I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG 
	-I"C:\Users\Doug\DOCUME~1\R\WIN-LI~1\3.6\opencv\include\opencv2" 
	-I"C:\Users\Doug\DOCUME~1\R\WIN-LI~1\3.6\opencv\include" 
	-I"C:\Users\Doug\DOCUME~1\R\WIN-LI~1\3.6\opencv\x86\mingw\bin" 
	-I"C:/Users/Doug/Documents/R/win-library/3.6/Rcpp/include" 
	-I"C:/Users/Doug/Documents/R/win-library/3.6/RcppArmadillo/include"     
	-IC:/Users/Doug/Documents/R/win-library/3.6/Rcpp/include   
	-O2 -Wall  -mtune=generic -c visionModule.cpp -o visionModule.o

c:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o Rvision.dll tmp.def RcppExports.o visionModule.o 
	-LC:\Users\Doug\DOCUME~1\R\WIN-LI~1\3.6\opencv\x86\mingw\lib 
	-lopencv_calib3d430 
	-lopencv_core430 
	-lopencv_features2d430 
	-lopencv_flann430 
	-lopencv_gapi430 
	-lopencv_highgui430 
	-lopencv_imgcodecs430 
	-lopencv_imgproc430 
	-lopencv_ml430 
	-lopencv_objdetect430 
	-lopencv_photo430 
	-lopencv_stitching430 
	-lopencv_video430 
	-lopencv_videoio430 
	-LC:/PROGRA~1/R/R-36~1.0/bin/i386 -lR

visionModule.o:visionModule.cpp:(.text+0x25b): undefined reference to `cv::destroyWindow(std::string const&)'
visionModule.o:visionModule.cpp:(.text+0x95e): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
visionModule.o:visionModule.cpp:(.text+0x971): undefined reference to `cv::getWindowImageRect(std::string const&)'
visionModule.o:visionModule.cpp:(.text+0x989): undefined reference to `cv::resizeWindow(std::string const&, int, int)'
visionModule.o:visionModule.cpp:(.text+0x9cf): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
visionModule.o:visionModule.cpp:(.text+0xb00): undefined reference to `cv::namedWindow(std::string const&, int)'
visionModule.o:visionModule.cpp:(.text+0xb30): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
visionModule.o:visionModule.cpp:(.text+0x24fe): undefined reference to `cv::VideoWriter::open(std::string const&, int, int, double, cv::Size_<int>, bool)'
visionModule.o:visionModule.cpp:(.text+0xad8d): undefined reference to `cv::imread(std::string const&, int)'
visionModule.o:visionModule.cpp:(.text+0xb338): undefined reference to `cv::imread(std::string const&, int)'
visionModule.o:visionModule.cpp:(.text+0xb887): undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
visionModule.o:visionModule.cpp:(.text+0x1af1b): undefined reference to `cv::getTextSize(std::string const&, int, double, int, int*)'
visionModule.o:visionModule.cpp:(.text+0x1e5b7): undefined reference to `cv::putText(cv::_InputOutputArray const&, std::string const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
visionModule.o:visionModule.cpp:(.text+0x23501): undefined reference to `cv::selectROIs(std::string const&, cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, bool, bool)'
visionModule.o:visionModule.cpp:(.text+0x23e16): undefined reference to `cv::setMouseCallback(std::string const&, void (*)(int, int, int, int, void*), void*)'
visionModule.o:visionModule.cpp:(.text+0x27b3d): undefined reference to `cv::imreadmulti(std::string const&, std::vector<cv::Mat, std::allocator<cv::Mat> >&, int)'
visionModule.o:visionModule.cpp:(.text+0x28540): undefined reference to `cv::VideoCapture::open(std::string const&, int)'
visionModule.o:visionModule.cpp:(.text+0x28945): undefined reference to `cv::VideoCapture::open(std::string const&, int)'
visionModule.o:visionModule.cpp:(.text+0x29ed9): undefined reference to `cv::VideoWriter::open(std::string const&, int, int, double, cv::Size_<int>, bool)'
collect2.exe: error: ld returned 1 exit status

no DLL was created
ERROR: compilation failed for package 'Rvision'
* removing 'C:/Users/Doug/Documents/R/win-library/3.6/Rvision'
* restoring previous 'C:/Users/Doug/Documents/R/win-library/3.6/Rvision'
Warning in install.packages :
  installation of package ‘C:/Users/Doug/Documents/R/win-library/3.6/Rvision_0.4.0.tar.gz’ had non-zero exit status

I can find the rvision.tar.gz file and have tried to install it from within Rstudio using "install packages" but no luck. The same output as above appears. 
thanks.

**Comment by sjmgarnier** [comment]
@dougmills There have been some changes to ROpenCVLite to make it CRAN-compatible and I haven't yet found the time to update the installation instructions of trackR. Here is what you need to do: 

```{r}
install.packages("ROpenCVLite")   # This will install ROpenCVLite from CRAN
library(ROpenCVLite)   # This will launch the installation of OpenCV. Just reply 
                       # "yes" when asked. This will take some time. 

remotes::install_github("swarm-lab/Rvision")
remotes::install_github("swarm-lab/trackR")

library(trackR)
```

**Comment by dougmills** [comment]
Thanks so much for the prompt reply. 
After the OpenCV install I ran 
 
`remotes::install_github("swarm-lab/Rvision")`

but got the same/similar output as before:

`ERROR: compilation failed for package 'Rvision'
* removing 'C:/Users/Doug/Documents/R/win-library/3.6/Rvision'
* restoring previous 'C:/Users/Doug/Documents/R/win-library/3.6/Rvision'
Error: Failed to install 'Rvision' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Doug/AppData/Local/Temp/Rtmp63nqa7/file25e03f2047a8/Rvision_0.4.0.tar.gz’ had non-zero exit status`

**Comment by sjmgarnier** [comment]
@dougmills Windows is the bane of my programming life :-) What is the version of Rtools that you are using? It should be 3.5 for your version of R.

**Comment by dougmills** [comment]
Hi Simon,
I gathered as much from previous posts. Sorry :)
Yes, RTools 3.5.
I had to revert back to 3.5 as I couldn't get OpenCV to install using RTools4.

**Comment by sjmgarnier** [comment]
@dougmills Yes, that's because Rtools 4.x is for using with R 4.x, not R 3.x. 

Can you try the following: 

```r
remotes::install_github("swarm-lab/ROpenCVLite")   # This will install the latest 
                       # dev version of ROpenCVLite from 
library(ROpenCVLite)   
installOpenCV()   # This will launch the installation of OpenCV. Just reply 
                  # "yes" when asked if you want to reinstall it. 
                  # This will take some time. 

remotes::install_github("swarm-lab/Rvision")
remotes::install_github("swarm-lab/trackR")

library(trackR)

```

**Comment by dougmills** [comment]
Thank you @sjmgarnier , that worked !

**Comment by sjmgarnier** [comment]
@dougmills I also pushed the new version of ROpenCVLite to CRAN so that nobody runs into this issue again.
