### ISSUE TITLE
An example .csv file of the tracked video

### ISSUE THREAD

**Issue by Sheethalvr** [swarm-lab/trackR#22]
I have no issues with the installations. I was wondering if an example .csv file could be provided, listing all the parameters tracked from the video.

Cheers!!

**Comment by sjmgarnier** [comment]
@Sheethalvr Sorry for the late response. I couldn't work on this project for a while. A new version of the software is out and I update the documentation with a description of the output data here: https://swarm-lab.github.io/trackR/articles/z3_trackR.html#7-output-data
