### ISSUE TITLE
Warning: Error in moduleUI: could not find function "moduleUI"   message

### ISSUE THREAD

**Issue by treesearcher** [swarm-lab/trackR#24]
Hi, 

Trying to get trackR up and running.  Had some issues with file paths early on (multi user computer) with RopenCVLite, but seem to have that sorted.  

R 4.0.5
R studio 1.4.1106
Packages up to date

when I try to run trackR with the 

trackR::trackR()  command,  It opens, but the screen is black, I get the following message, 

Warning: Error in moduleUI: could not find function "moduleUI"
  82: verticalTabsetPanel
  70: ui [C:\Users\Matt\Documents\R\win-library\4.0\trackR\trackR/app.R#12]

Thanks!

**Comment by sjmgarnier** [comment]
@treesearcher Did you load the library (`library(trackR)`) before launching the app?

**Comment by treesearcher** [comment]
Hi!  

Wow! quick feed back! thanks!  
Yes, sorry forgot to mention it is loaded.

**Comment by treesearcher** [comment]
AHHH NO! Soo sorry! 

IT wasn't loaded!!!! 

IT WORKS!

**Comment by sjmgarnier** [comment]
@treesearcher Good, because I have zero time for fixing bugs at the moment :-)
