### ISSUE TITLE
Crash on mask, does not create/can't find csv output 

### ISSUE THREAD

**Issue by treesearcher** [swarm-lab/trackR#25]
Hi, 
Sorry to bother again, 

TrackR now opens no problem and I can move though vid upload, and background, as soon as I click on step 3 to mask (which I don't NEED to do), it crashes with following error 

> trackR::trackR()

Listening on http://127.0.0.1:7350
Warning: Error in setTo: mask is not an 8U single-channel 'Image' object
  2: shiny::runApp
  1: trackR::trackR

 (just the windows close, and R studio still running) 
 This is not affected by opening shiny in the browser. 

So I can skip the mask step and keep going, and all works fine.  I can save my settings to any desired folder, even make new folders no problem, and upload past settings and background .png files. 

When I finally "start tracking" it runs, usually shows a status bar to 80-90 % then closes the status bar, but with no noted saved output.  I've tried making new folders etc.  no change, running in the browser, no change.   Again, it will save to folder the background image, and and setting parameters no problem! 

There is no error message, it just exits the status bar window, and I could run again. 

I did note, that if I accidently delete all a single field in setting parameters in the separation module it crashes as well (windows close) not sure if that's related.  (I can enter my own parameters provided I do not have a null answer in the field.

Warning: Error in if: missing value where TRUE/FALSE needed
  2: shiny::runApp
  1: trackR::trackR

I've tried assorted video files (all .mp4), and these are relatively short ~ 5 seconds at 30 FPS
I also searched to see if the output was save somewhere else, no luck. 

Sorry to bother, suggestions? 

Windows 10 
R 4.0.5
R studio 1.4.1106
Packages up to date

Thanks!

**Comment by sjmgarnier** [comment]
@treesearcher Argh, yes, that's probably because you're using the very last version of Rvision. I haven't updated trackR to work with it yet. I just pushed a quick fix for the trackR app, you should be able to get it by reinstalling the trackR package. I will work on the other apps in the package as soon as I can.

**Comment by treesearcher** [comment]
IT WORKS!!! ;) 

Thanks!
