### ISSUE TITLE
Error in display: unused argument (interp)

### ISSUE THREAD

**Issue by Juchartr** [swarm-lab/trackR#26]
Hello, 

I've been using trackR for a while now, and today I can't use it. Each time I run the trackR() code or trackR(launch.browser = rstudioapi::viewer) the module appear then stop. I've got the following warning: Error in _display: unused argument (interp). 
All packages are up to date, and trackR has been reinstalled. R is also up to date. 

Any idea of what's wrong and how I can fix it ?

Thanks a lot :)

**Comment by sjmgarnier** [comment]
@Juchartr Is this on a new install? Have you changed/updated anything since the last time it was working?

**Comment by Juchartr** [comment]
I was having an issue with a video, so I uninstall it and reinstall it. When I did the new install, I also updated Rvision (because I couldn't install it without the update).

**Comment by sjmgarnier** [comment]
@Juchartr Ok. Can I have the version number of R, Rvision, ROpenCVLite, and trackR installed on your machine? And for good measure, your operating system as well. I'll see if I can reproduce the bug here.

**Comment by Juchartr** [comment]
R version 4.0.5 
Rvision version 0.6.0
ROpenCVLite version 4.51.0
trackR version 0.5.1

I am working under Windows 10

**Comment by sjmgarnier** [comment]
@Juchartr I'm afraid I can't reproduce the error on my Windows 10 install. Everything works as expected here. My hunch is that Rvision may have been loaded in R's memory when you updated the package and the links to the underlying compiled C++ code weren't updated. If that's the case, restarting R should do the trick.

**Comment by Juchartr** [comment]
@sjmgarnier I uninstall everything and reinstall it, and it seems to work now. Thank you for trying to reproduce the error; it is appreciated.
