### ISSUE TITLE
Issue with the trackPlayer function

### ISSUE THREAD

**Issue by serranito-bruno** [swarm-lab/trackR#29]
Hello,
I really want to thank you for your work.
I am currently working with TrackR and it works quite well.
However when I want to click on "export" using the trackPlayer function, the window closes and a warning message appears in the console:
Warning: Error in new_CppObject_xp: Unable to open output.
  [No stack trace available] 

Although my R session still seems to be processing, nothing else happened.

The same thing happened with the videoFixer function.
Do you have any idea how to solve this problem?

**Comment by serranito-bruno** [comment]
Update -
I finally manage to fix this issue. It was caused by an out dated version of the codex 'OpenH254' used by OpenCV. 
The thread can now be closed.

**Comment by Toshea111** [comment]
Hello,

I am experiencing the same issue, are you able to detail the process for updating the codex?

Best wishes,

Thomas
