### ISSUE TITLE
Error when installing trackR

### ISSUE THREAD

**Issue by AAleotti** [swarm-lab/trackR#34]
After following all the steps to install ROpenCVLite from here: https://swarm-lab.github.io/ROpenCVLite/articles/install.html

I tried to install trackR, but I get the following error:

Downloading GitHub repo swarm-lab/trackR@HEAD
Downloading GitHub repo azureblue/CEC@HEAD
── R CMD build ─────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\Alebo\AppData\Local\Temp\RtmpozWK4H\remotes2b1c61882b52\azureblue-cec-3437a6e/DESCRIPTION' ... 
─  preparing 'CEC':
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a 'data/datalist' file should be added
─  building 'CEC_0.10.3.tar.gz'
   
Installazione pacchetto in ‘C:/Users/Alebo/AppData/Local/R/win-library/4.3’
(perché ‘lib’ non è specificato)
 installing source* package 'CEC' ...
** using staged installation
** libs
using C++ compiler: 'G__~1.EXE (GCC) 12.2.0'
using C++11
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG     -I"C:/rtools43/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c cec_r.cpp -o cec_r.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG     -I"C:/rtools43/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c cec_starter.cpp -o cec_starter.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG     -I"C:/rtools43/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c init.cpp -o init.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG     -I"C:/rtools43/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c models/cov_utils.cpp -o models/cov_utils.o
models/cov_utils.cpp: In function 'bool cholesky(const cec::mat&, cec::mat&)':
models/cov_utils.cpp:24:12: error: too few arguments to function 'void dpotrf_(const char, const int, double, const int, int*, size_t)'
   24 |     dpotrf_("U", &n, dst.data(), &n, &info);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/PROGRA~1/R/R-43~1.0/include/R_ext/Lapack.h:40,
                 from models/cov_utils.cpp:4:
C:/PROGRA~1/R/R-43~1.0/include/R_ext/Lapack.h:825:10: note: declared here
  825 | F77_NAME(dpotrf)(const char uplo, const int n,
      |          ^~~~~~
C:/PROGRA~1/R/R-43~1.0/include/R_ext/RS.h:77:25: note: in definition of macro 'F77_CALL'
   77 | # define F77_CALL(x)    x ## _
      |                         ^
C:/PROGRA~1/R/R-43~1.0/include/R_ext/Lapack.h:825:1: note: in expansion of macro 'F77_NAME'
  825 | F77_NAME(dpotrf)(const char uplo, const int n,
      | ^~~~~~~~
models/cov_utils.cpp: In function 'void cec::multiply(const mat&, const mat&, mat&)':
models/cov_utils.cpp:56:11: error: too few arguments to function 'void dsymm_(const char, const char, const int, const int, const double, const double, const int, const double, const int, const double, double, const int, size_t, size_t)'
   56 |     dsymm_("L", "L", &n, &n, &one, a.data(), &n, b.data(), &n, &zero, dst.data(), &n);
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/PROGRA~1/R/R-43~1.0/include/R_ext/BLAS.h:233:10: note: declared here
  233 | F77_NAME(dsymm)(const char side, const char uplo, const int *m,
      |          ^~~~~
C:/PROGRA~1/R/R-43~1.0/include/R_ext/RS.h:77:25: note: in definition of macro 'F77_CALL'
   77 | # define F77_CALL(x)    x ## _
      |                         ^
C:/PROGRA~1/R/R-43~1.0/include/R_ext/BLAS.h:233:1: note: in expansion of macro 'F77_NAME'
  233 | F77_NAME(dsymm)(const char side, const char uplo, const int *m,
      | ^~~~~~~~
models/cov_utils.cpp: In function 'bool cec::invert(const mat&, mat&)':
models/cov_utils.cpp:64:12: error: too few arguments to function 'void dpotri_(const char, const int, double, const int, int*, size_t)'
   64 |     dpotri_("U", &n, dst.data(), &n, &info);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/PROGRA~1/R/R-43~1.0/include/R_ext/Lapack.h:831:10: note: declared here
  831 | F77_NAME(dpotri)(const char uplo, const int n,
      |          ^~~~~~
C:/PROGRA~1/R/R-43~1.0/include/R_ext/RS.h:77:25: note: in definition of macro 'F77_CALL'
   77 | # define F77_CALL(x)    x ## _
      |                         ^
C:/PROGRA~1/R/R-43~1.0/include/R_ext/Lapack.h:831:1: note: in expansion of macro 'F77_NAME'
  831 | F77_NAME(dpotri)(const char uplo, const int n,
      | ^~~~~~~~
models/cov_utils.cpp: In member function 'bool cec::eigenvalues_calculator::eigenvalues(const cec::mat&, double*) const':
models/cov_utils.cpp:75:11: error: too few arguments to function 'void dsyev_(const char, const char, const int, double, const int, double, double, const int, int*, size_t, size_t)'
   75 |     dsyev_("N", "U", &n, tmp.data(), &n, res, workspace.data(), &workspace.size, &info);
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/PROGRA~1/R/R-43~1.0/include/R_ext/Lapack.h:1242:10: note: declared here
 1242 | F77_NAME(dsyev)(const char jobz, const char uplo,
      |          ^~~~~
C:/PROGRA~1/R/R-43~1.0/include/R_ext/RS.h:77:25: note: in definition of macro 'F77_CALL'
   77 | # define F77_CALL(x)    x ## _
      |                         ^
C:/PROGRA~1/R/R-43~1.0/include/R_ext/Lapack.h:1242:1: note: in expansion of macro 'F77_NAME'
 1242 | F77_NAME(dsyev)(const char jobz, const char uplo,
      | ^~~~~~~~
make: *** [C:/PROGRA~1/R/R-43~1.0/etc/x64/Makeconf:272: models/cov_utils.o] Error 1
ERROR: compilation failed for package 'CEC'
* removing 'C:/Users/Alebo/AppData/Local/R/win-library/4.3/CEC'
Downloading GitHub repo azureblue/CEC@HEAD
Skipping CEC, it is already being installed
── R CMD build ─────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\Alebo\AppData\Local\Temp\RtmpozWK4H\remotes2b1c37f822b0\swarm-lab-trackR-be22b20/DESCRIPTION' ...
─  preparing 'trackR': (500ms)
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'trackR_0.5.3.tar.gz'
   
Installazione pacchetto in ‘C:/Users/Alebo/AppData/Local/R/win-library/4.3’
(perché ‘lib’ non è specificato)
ERROR: dependency 'CEC' is not available for package 'trackR'
* removing 'C:/Users/Alebo/AppData/Local/R/win-library/4.3/trackR'
Warning messages:
1: In i.p(...) :
  l'installazione del pacchetto ‘C:/Users/Alebo/AppData/Local/Temp/RtmpozWK4H/file2b1c63596d19/CEC_0.10.3.tar.gz’ ha uno stato di uscita non-zero
2: In i.p(...) :
  l'installazione del pacchetto ‘C:/Users/Alebo/AppData/Local/Temp/RtmpozWK4H/file2b1c45ba4aea/trackR_0.5.3.tar.gz’ ha uno stato di uscita non-zero

**To Reproduce**
The command I used was the following: 
remotes::install_github("swarm-lab/trackR")

**Computer (please complete the following information):**
 - Operating system: Windows 
 - Version: 11 Home

**R (please complete the following information):**
 - R version: 4.3.0
 - Rvision version: 0.7.0
 - shiny version: 1.7.4

**Comment by sjmgarnier** [comment]
@AAleotti Try installing CEC first with `install.packages("CEC")`. This has been fixed in the develop branch but I haven't yet pushed it to the main branch.

**Comment by AAleotti** [comment]
Thanks for your reply - this has fixed the problem!

Thanks again =)
