### ISSUE TITLE
Crash at start on the develop branch

### ISSUE THREAD

**Issue by yohann-chemtob** [swarm-lab/trackR#35]
I installed trackR with remotes::install_github("swarm-lab/trackR@develop") to get the stack video feature.
When I'm running trackR(), the interface open for a second and crash.
The full error message is:
`
Listening on http://127.0.0.1:5482
Warning: Error in isVideoStack: could not find function "isVideoStack"
  98: renderUI [D:/Users/Yohann/Documents/R/win-library/4.1/trackR/modules/trackR/videoServer.R#20]
  97: func
  84: renderFunc
  83: output$videoStatus
   2: shiny::runApp
   1: trackR
Warning: Error in isVideoStack: could not find function "isVideoStack"
  98: renderUI [D:/Users/Yohann/Documents/R/win-library/4.1/trackR/modules/trackR/videoServer.R#92]
  97: func
  84: renderFunc
  83: output$rangeSlider
   2: shiny::runApp
   1: trackR
Warning: Error in isVideoStack: could not find function "isVideoStack"
  98: renderUI [D:/Users/Yohann/Documents/R/win-library/4.1/trackR/modules/trackR/videoServer.R#107]
  97: func
  84: renderFunc
  83: output$qualitySlider
   2: shiny::runApp
   1: trackR
Warning: Error in isVideoStack: could not find function "isVideoStack"
  98: renderUI [D:/Users/Yohann/Documents/R/win-library/4.1/trackR/modules/trackR/videoServer.R#114]
  97: func
  84: renderFunc
  83: output$videoSlider
   2: shiny::runApp
   1: trackR
Warning: Error in isVideoStack: could not find function "isVideoStack"
  2: shiny::runApp
  1: trackR
Warning: Error in isVideoStack: could not find function "isVideoStack"
  98: renderUI [D:/Users/Yohann/Documents/R/win-library/4.1/trackR/modules/trackR/videoServer.R#20]
  97: func
  84: renderFunc
  83: output$videoStatus
   2: shiny::runApp
   1: trackR
Warning: Error in isVideoStack: could not find function "isVideoStack"
  2: shiny::runApp
  1: trackR
`
Looking into the source code, I couldn't locate the function isVideoStack.

**Computer:**
 - Operating system: Windows 10

**R:**
 - R version: 4.1.3
 - Rvision version: 0.6.0
 - shiny version: 1.7.4.1

**Comment by sjmgarnier** [comment]
@yohann-chemtob Please update to the latest version of ROpenCVLite and Rvision and try again.

**Comment by yohann-chemtob** [comment]
It fixed the issue, thanks!
