### ISSUE TITLE
 TrackR extremely slow what to do?

### ISSUE THREAD

**Issue by Sophie-Genaux** [swarm-lab/trackR#37]
Bonjour,

Je dois utiliser trackR afin d'analyser des vidéos de comportement sur des poissons mais trackR est extrement lent (32h pour analyser une vidéo d'une heure) j'ai changer de versions de R et de Rstudio afin de voir si les performances ne s'améliorait pas mais je n'ai eu aucune amélioration.
J'utilise un pc très puissant qui tourne sous un intel I9 12ème génération avec une très bonne carte graphique et 32gb de ram

Pourriez vous m'aider?
______________________
Good morning,

I have to use trackR to analyze behavior videos on fish but trackR is extremely slow (32 hours to analyze a one hour video) I changed versions of R and Rstudio to see if the performance is not good. It wasn't improving but I didn't have any improvement.
I use a very powerful PC which runs an Intel I9 12th generation with a very good graphics card and 32GB of RAM

Could you help me?

**Comment by sjmgarnier** [comment]
@Sophie-Genaux Est-ce que vous pourriez m'envoyer une vidéo exemple pour que je comprenne bien le problème ? Vous pouvez me contacter à l'adresse suivante pour cela : garnier@njit.edu.

**Comment by Sophie-Genaux** [comment]
Merci pour votre réponse, je vous ai envoyé la vidéo sur votre adresse mail.

**Comment by sjmgarnier** [comment]
@Sophie-Genaux I managed to finds some time to work on the performance issue (hopefully, it's not too late for you). I've implemented them into the redesign of trackR that I'm currently preparing on the develop branch of the repository (https://github.com/swarm-lab/trackR/tree/develop). You can install it as follows: 

```r
remotes::install_github("swarm-lab/trackR@develop")
```

You may also have to reinstall ROpenCVLite and Rvision first if you do not have their latest versions already (4.90.0 and 0.8.0, respectively). 

Note that I'm in the process of heavily modifying trackR, so it will not look and work exactly as the version you are currently using. Also, it is still under development, so it's likely to have bugs I haven't found yet and the documentation is not yet up to date. I'm happy to jump on a quick video call to show you the main differences, just contact me by email for that.

**Comment by Sophie-Genaux** [comment]
Thank you for this new version, it is indeed faster and works without problem with the videos that I have to process.
Have a good day

**Comment by sjmgarnier** [comment]
@Sophie-Genaux Great! I will close this issue then.

**Comment by Sophie-Genaux** [comment]
Could you just give me some details on tab 4 because I have some difficulty selecting only my subject
Thank you

**Comment by sjmgarnier** [comment]
@Sophie-Genaux This is a conversation that might be better suited for a video call. There are many reasons why this can happen, from issues with the experimental setup to software parameterization. I can send a video link in response to your email if you would like.

**Comment by Sophie-Genaux** [comment]
Thanks, I think a video call is a good idea
