### ISSUE TITLE
Not being able to install

### ISSUE THREAD

**Issue by helderhugo** [swarm-lab/trackR#4]
##### System information (version)

- trackR => 0.1
- Rvision => 0.3.1
- ROpenCVLite => 0.1.34.3
- Operating System / Platform => Mac OS Mojave
- R => 3.5.1
- CMake => 3.12
##### Detailed description

After pre-installing the requirements, I'm not able to install trackR itself. After 'installing vignettes' and 'testing if installed package can be loaded' I get the following errors:
```.r
installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘sum’ in package ‘Rvision’
Creating a new generic function for ‘mean’ in package ‘Rvision’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘Rvision’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs/Rvision.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs/Rvision.so, 6): Library not loaded: @rpath/libopencv_dnn.3.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs/Rvision.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision’
Installation failed: Command failed (1)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/sc/zlrwq02n6p7361176t5hjvdm0000gn/T/RtmpPBaWDk/devtools31d875abd819/swarm-lab-trackR-b01cb07'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 

ERROR: dependency ‘Rvision’ is not available for package ‘trackR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/trackR’
Installation failed: Command failed (1)
```
##### Steps to reproduce

```.r
devtools::install_github("swarm-lab/trackR")
library(trackR)
```

**Comment by sjmgarnier** [comment]
@helderhugo This is weird. Rvision should have been automatically installed. Let me check.

**Comment by sjmgarnier** [comment]
@helderhugo Try again. It works on my Macbook now.

**Comment by helderhugo** [comment]
I still got the same error... Do you think it could be a problem with cmake on my machine?

**Comment by sjmgarnier** [comment]
@helderhugo This is weird. I could replicate your problem but then made a tiny change that solved it here. Do you have the very latest version of devtools installed? There has been some changes to it that I think were responsible of this error.

**Comment by helderhugo** [comment]
@sjmgarnier I did install the last versions of R, CMake and devtools (via RStudio). I also tried on my iMAC: everything goes well until the last part, in which there is a test to check '**if Rvision can be loaded**'. Then I got the exactly same error as before...

Any ideas how to solve it?

**Comment by sjmgarnier** [comment]
@helderhugo Ok, this is becoming very strange. Just to double check everything: 

1. You have the latest version of R (3.5.1)
2. You have the latest version of devtools (2.0.0)
3. You have the latest version of Cmake (3.12.3)
4. You have updated all your packages to their latest version and restarted R/RStudio. This is mostly to make sure nothing weird is loaded in memory while trying to install trackR. 

Two questions now:

1. Is the package ROpenCVLite installed on your system? It should have installed automatically before trackR. If it is installed, what version is it?
2. Is the package Rvision installed on your system? It should have installed automatically before trackR. If it is installed, what version is it?

**Comment by helderhugo** [comment]
@sjmgarnier 1, 2, 3, 4 are checked, I have all these versions (I removed completely R from both machines and installed it from scratch).

1. The package ROpenCVLite is installed on the system. I can load it with `library(ROpenCVLite)`.
2 I'm not able to install Rvision: installation starts well but after the step ** **testing if installed package can be loaded** I get the same error:

**Error: package or namespace load failed for ‘Rvision’ in dyn.load(file, DLLpath = DLLpath, ...):**

**Comment by helderhugo** [comment]
@sjmgarnier I did... I trying something else now, and I'll let you know whether I have success or not. (All other swarmlab packages work just fine)

**Comment by sjmgarnier** [comment]
@helderhugo Just to make sure, you have the latest command line tools for Mac, right?

**Comment by helderhugo** [comment]
@sjmgarnier Yes I updated it before trying to install the package. No luck with Macs! I'm trying in a windows machine I have, just in case, but if doesn't work unfortunately I'll have to give up :/

**Comment by sjmgarnier** [comment]
@helderhugo This is incomprehensible. I develop on Mac. If there is a platform on which it shouldn't have any problem installing, it's that one. Can you chat now? I have about 30 minutes. If yes, DM me on Twitter, I'll send you a link.

**Comment by sjmgarnier** [comment]
@helderhugo After reading more carefully your first message, I think I might have a clue what is happening here. After installing ROpenCVLite, what do the following commands return?

`ROpenCVLite::opencvConfig("libs)`

`ROpenCVLite::opencvConfig("cflags)`

This (`Library not loaded: @rpath/libopencv_dnn.3.2.dylib`) makes me think that you have an older version of OpenCV installed on your machine that is conflicting with the version installed by ROpenCVLite.

**Comment by helderhugo** [comment]
Sorry @sjmgarnier I was off for a bit.

This is what I get:

```
> ROpenCVLite::opencvConfig("libs")
-L/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ROpenCVLite/opencv/lib -lopencv_dnn -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core 
> ROpenCVLite::opencvConfig("cflags")
-I/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ROpenCVLite/opencv/include/opencv -I/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ROpenCVLite/opencv/include
> 
```

**Comment by sjmgarnier** [comment]
@helderhugo Ok. It looks like ROpenCVLite is correctly installed. What's not clear to me is why when installing Rvision it is trying to link against OpenCV 3.2 (ROpenCVLite installs OpenCV 3.4.1). Can you show me the output of `ROpenCVLite::opencvVersion()`? And can you show me the exact command lines you have used to run the installation of Rvision? And also the entire console output?

**Comment by helderhugo** [comment]
@sjmgarnier OK. So here it is:

```
> ROpenCVLite::opencvVersion()
[1] "prefix=/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ROpenCVLite/opencv"
[2] "Version: 3.4.3"                                                                          
> 
```
This is the command I used for installing Rvision by itself, after the first installation of trackR didn't work. I also include the entire console output:

```
> devtools::install_github("swarm-lab/Rvision")
Downloading GitHub repo swarm-lab/Rvision@master
✔  checking for file ‘/private/var/folders/wc/6nzs_tys3mxd2hdr7ldkf8qm0000gn/T/RtmpFSmrmP/remotes49601c002923/swarm-lab-Rvision-0eed5f8/DESCRIPTION’ ...
─  preparing ‘Rvision’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Rvision_0.3.1.tar.gz’
   
* installing *source* package ‘Rvision’ ...
** libs
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG `/Library/Frameworks/R.framework/Resources/bin/Rscript -e 'ROpenCVLite::opencvConfig("cflags")'` -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include" -I/usr/local/include  `/Library/Frameworks/R.framework/Resources/bin/Rscript -e 'Rcpp:::CxxFlags()'` -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG `/Library/Frameworks/R.framework/Resources/bin/Rscript -e 'ROpenCVLite::opencvConfig("cflags")'` -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include" -I/usr/local/include  `/Library/Frameworks/R.framework/Resources/bin/Rscript -e 'Rcpp:::CxxFlags()'` -fPIC  -Wall -g -O2  -c visionModule.cpp -o visionModule.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o Rvision.so RcppExports.o visionModule.o -L/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ROpenCVLite/opencv/lib -lopencv_dnn -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core -llapack -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘sum’ in package ‘Rvision’
Creating a new generic function for ‘mean’ in package ‘Rvision’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘Rvision’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs/Rvision.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs/Rvision.so, 6): Symbol not found: __ZN2cv18getWindowImageRectERKNS_6StringE
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs/Rvision.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision/libs/Rvision.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rvision’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/wc/6nzs_tys3mxd2hdr7ldkf8qm0000gn/T//RtmpFSmrmP/file49602a8b1145/Rvision_0.3.1.tar.gz’ had non-zero exit status
> 
```

**Comment by sjmgarnier** [comment]
@helderhugo This is a very different error from the one you originally posted. I suspect that you're using a non-standard compiler (like clang installed via homebrew instead of the standard clang from Mac OS Xcode; or maybe you have a version of Xcode that is too old for your current system). If you open a terminal and type `clang --version`, what's the output?

**Comment by sjmgarnier** [comment]
@helderhugo Also, it could be an issue with the R version that you are using. Did you install CRAN R or one from Homebrew? It's possible the R version from Homebrew is compiled using gcc, which would cause this kind of problems when trying to compile with the standard clang compiler on Mac. It looks like this is the issue for several packages using Rcpp (Rvision depends on it) when Rcpp is compiled with gcc instead of clang.

**Comment by sjmgarnier** [comment]
@helderhugo On this note, are you using a custom ~/.R/Makevars? If yes, can you post its content here.

**Comment by helderhugo** [comment]
Here is the clang:

```
wik89:~ iaincouzin$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by helderhugo** [comment]
I installed R from CRAN. I just used homebrew to install python and OpenCV in a virtual environment.

**Comment by helderhugo** [comment]
Also @sjmgarnier I'm not using a custom ~/.R/Makevars

**Comment by sjmgarnier** [comment]
@helderhugo We have different versions of clang. The rest seems to be the same between our two systems. I'm going to install your version of clang, see if I can reproduce the error.

**Comment by helderhugo** [comment]
Alright! If that's the problem I try to install your version.

**Comment by sjmgarnier** [comment]
@helderhugo I was using clang provided by Command Line Tools, which was apparently an older version than that provided with Xcode (why would they do this? no idea). I removed it, installed the latest version of Xcode (with clang-1000.11.45.5) and I'm still able to compile and install Rvision without problem. Your version of Xcode is slighly out of date (you have clang-1000.11.45.2), but I doubt now this is the cause of the problem (though it might be worth updating Xcode to its latest version, just in case). So, the good news is that Rvision works on Mac. The bad news is that it doesn't work on your Mac and I'm still at a loss to explain it.

**Comment by Sheethalvr** [comment]
This thread helped in fixing the error messages. But after finally being able to fix issues with ROpenCVLite and Rvision, it still spit out an error saying -
package ‘rlang’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘rlang’

I installed 'rlang' from the source (install.packages("rlang", type = "source") )and then ran -
devtools::install_github("swarm-lab/trackR")

Now, it ran pretty smoothly and got this -
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (trackR)

**Comment by sjmgarnier** [comment]
@Sheethalvr This is a problem with the rlang package, not trackR. My guess is that rlang is loaded while you're trying to do the installation and therefore prevents R from updating it. I suggest restarting R and updating rlang before trying to install trackR again.
