### ISSUE TITLE
Trouble selecting a video

### ISSUE THREAD

**Issue by MandaFry** [swarm-lab/trackR#6]
##### System information (version)
- trackR => 0.1
- Rvision => 0.3.1
- ROpenCVLite => 0.1.34.3
- Operating System / Platform => Windows 10 64bit
- R => 3.5.1
- CMake => 3.12
-->

##### Detailed description

After installing and using 'trackR()' the window pops up to select a video file but I get the following message;

# trackR()

Listening on http://127.0.0.1:6907
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:856)
warning: C:/Users/789826/Documents/Documents/Fish Vids/F1_Trial1_07.05.18_x264.avi (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:857)

**Comment by sjmgarnier** [comment]
@MandaFry Looks like a codec issue. Can you try with the video at this address and let me know what happens? https://github.com/vivekhsridhar/tracktor/blob/master/videos/termite_video.mp4?raw=true

**Comment by MandaFry** [comment]
@sjmgarnier unfortunately a similar thing happens. When I tried with your video I get; 
Listening on http://127.0.0.1:6907
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:856)
warning: C:/Users/789826/Documents/Desktop/termite_video.mp4 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:857)

**Comment by sjmgarnier** [comment]
@MandaFry Thanks. I can reproduce the error on a Windows machine. I think the problem is with the way Windows handles paths to files, which is different from what Mac and Linux do. I'll try to work on a fix asap.

**Comment by MandaFry** [comment]
@sjmgarnier thank you very much for your help, and for helping identifying the issue. I have reinstalled trackR and it has now loaded the video, thank you :)

**Comment by sjmgarnier** [comment]
@MandaFry No problem. See you at the next bug :-)
