### ISSUE TITLE
Video loads upside-down

### ISSUE THREAD

**Issue by rkadrian** [swarm-lab/trackR#8]
##### System information (version)
- trackR => 0.1
- Rvision => 0.3.1
- ROpenCVLite => 0.1.34.3
- Operating System / Platform => Mac OS Mojave
- R => 3.5.1
- CMake => 3.12.4

##### Detailed description

I am loading a .MOV video originally taken on my iPhone 6 under the slo-mo function. This isn't a major issue, but the video appears to load upside-down. When I play the video elsewhere, I don't see the problem. I'm guessing it's something to do with how the video was saved from my iPhone? (Trying to extract a background image from more than 1 frame keeps crashing the program so I've had a chance to retry many times!)

**Comment by sjmgarnier** [comment]
@rkadrian This is weird. Can you send me a video sample that causes that problem?
