### ISSUE TITLE
PNG mask upload error

### ISSUE THREAD

**Issue by rkadrian** [swarm-lab/trackR#9]
##### System information (version)
- trackR => 0.1
- Rvision => 0.3.1
- ROpenCVLite => 0.1.34.3
- Operating System / Platform => Mac OS Mojave
- R => 3.5.1
- CMake => 3.12

##### Detailed description

I have since solved this problem, but it's worth reporting regardless. I created a mask in Photoshop, using the background image that trackR created as a template to ensure that the dimensions were correct. However, when attempted to upload a .png of the mask in trackR, I received this error:

```
Warning: Error in _multiply: OpenCV(3.4.3) /private/var/folders/54/77m_hflx6zg823c2jcp4qy6w0000gn/T/RtmpJWnUlJ/R.INSTALL3f51c8836f8/ROpenCVLite/src/opencv-3.4.3/modules/core/src/arithm.cpp:659: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'

  52: <Anonymous>
```

Both the background image saved from trackR and the mask image were 1280 x 720 (the dimensions appeared to match). So, I resaved the mask as a .jpg, and it has uploaded to trackR successfully. It seems that the error occurs when the image is .png but not otherwise?

I apologize for flooding this space with random errors, but I am enjoying attempting to get this program to work for my experiment. It looks promising!

**Comment by sjmgarnier** [comment]
@rkadrian This is most likely because Photoshop saved by default the alpha (transparency) channel in the png file. The result is that your background image has 4 channels (R, G, B, alpha), while each frame of your video has only 3 (R, G, V). jpg doesn't have an alpha channel, that's why it worked.
